-- All fixtures and business writes are rolled back, including auth users.
begin;
do $$
declare c uuid; b uuid; z uuid; d uuid; p uuid; u uuid:=gen_random_uuid(); clerk uuid:=gen_random_uuid(); stranger uuid:=gen_random_uuid();
 sender uuid; receiver uuid; doc uuid; doc2 uuid; pay uuid; request uuid:=gen_random_uuid();
 payload jsonb; balance numeric; blocked boolean; old_address text;
begin
 insert into public.companies(code,name) values('NTD-VERIFY-'||left(u::text,8),'Verification only') returning id into c;
 insert into public.branches(company_id,code,name) values(c,'TEST','Test') returning id into b;
 insert into public.service_zones(company_id,code,name,color) values(c,'TEST','Test zone','#3174c6') returning id into z;
 insert into public.districts(zone_id,name) values(z,'Test district') returning id into d;
 insert into public.products(company_id,name,unit) values(c,'Test product','กล่อง') returning id into p;
 insert into auth.users(id,email) values(u,u::text||'@example.invalid'),(clerk,clerk::text||'@example.invalid'),(stranger,stranger::text||'@example.invalid');
 insert into public.profiles(id,company_id,branch_id,display_name,email,role) values(u,c,b,'Verifier',u::text||'@example.invalid','owner'),(clerk,c,b,'Clerk',clerk::text||'@example.invalid','clerk');
 perform set_config('request.jwt.claim.sub',u::text,true);
 sender:=public.save_party(jsonb_build_object('display_name','Test sender','phone','0990000001','address','Original address'));
 receiver:=public.save_party(jsonb_build_object('display_name','Test receiver','phone','0990000002','address','Receiver address'));
 perform public.save_party(jsonb_build_object('id',sender,'display_name','Test sender','phone','0990000001','address','Original address','credit_limit',1000,'credit_days',30));
 perform public.manage_setting('price',jsonb_build_object('product_id',p,'unit_price',40));
 payload:=jsonb_build_object('request_id',request,'sender',jsonb_build_object('id',sender,'display_name','Test sender','phone','0990000001','address','Original address'),'receiver',jsonb_build_object('id',receiver,'display_name','Test receiver','phone','0990000002','address','Receiver address'),'zone_id',z,'district_id',d,'payment_mode','CASH_DESTINATION','credit_days',0,'items',jsonb_build_array(jsonb_build_object('product_id',p,'description','Test product','unit','กล่อง','quantity',3,'unit_price',40,'weight',2,'fragile',false)),'extra_charge',0,'discount',0,'collect_now',false);
 doc:=public.issue_shipment(payload);
 if public.issue_shipment(payload)<>doc then raise exception 'FAIL: idempotency'; end if;
 if (select count(*) from public.shipments where company_id=c)<>1 then raise exception 'FAIL: duplicate document'; end if;
 select outstanding_amount into balance from public.shipment_register where id=doc;
 if balance<>120 then raise exception 'FAIL: destination cash prematurely marked paid'; end if;
 pay:=public.receive_payment(doc,50,'CASH','',gen_random_uuid());
 select outstanding_amount into balance from public.shipment_register where id=doc;
 if balance<>70 then raise exception 'FAIL: partial payment'; end if;
 blocked:=false;
 begin perform public.receive_payment(doc,71,'CASH','',gen_random_uuid()); exception when others then blocked:=true; end;
 if not blocked then raise exception 'FAIL: overpayment allowed'; end if;
 blocked:=false;
 begin perform public.set_shipment_status(doc,'CANCELLED','test cancellation'); exception when others then blocked:=true; end;
 if not blocked then raise exception 'FAIL: paid document cancelled'; end if;
 perform public.save_party(jsonb_build_object('id',sender,'display_name','Test sender','phone','0990000001','address','Updated address'));
 select sender_snapshot->>'address' into old_address from public.shipments where id=doc;
 if old_address<>'Original address' then raise exception 'FAIL: historical address changed'; end if;
 perform set_config('request.jwt.claim.sub',clerk::text,true);
 blocked:=false;
 begin perform public.save_party(jsonb_build_object('id',sender,'display_name','Test sender','phone','0990000001','address','Updated address','credit_days',365)); exception when others then blocked:=true; end;
 if not blocked then raise exception 'FAIL: clerk changed credit terms'; end if;
 blocked:=false;
 begin perform public.issue_shipment(jsonb_set(jsonb_set(payload,'{request_id}',to_jsonb(gen_random_uuid())),'{items,0,unit_price}','1')); exception when others then blocked:=true; end;
 if not blocked then raise exception 'FAIL: clerk changed price'; end if;
 doc2:=public.issue_shipment(jsonb_set(payload,'{request_id}',to_jsonb(gen_random_uuid())));
 if doc2=doc then raise exception 'FAIL: document number reuse'; end if;
 perform set_config('request.jwt.claim.sub',stranger::text,true);
 blocked:=false;
 begin perform public.issue_shipment(payload); exception when others then blocked:=true; end;
 if not blocked then raise exception 'FAIL: nonstaff issued document'; end if;
 execute 'set local role authenticated';
 if (select count(*) from public.shipments)<>0 then raise exception 'FAIL: nonstaff read documents'; end if;
 if (select count(*) from public.parties)<>0 then raise exception 'FAIL: nonstaff read customers'; end if;
 blocked:=false;
 begin update public.profiles set role='owner' where id=stranger; exception when insufficient_privilege then blocked:=true; end;
 if not blocked then raise exception 'FAIL: direct role write allowed'; end if;
 execute 'reset role';
 perform set_config('request.jwt.claim.sub',u::text,true);
 execute 'set local role authenticated';
 if (select count(*) from public.shipments)<>2 then raise exception 'FAIL: owner cannot read own documents'; end if;
 blocked:=false;
 begin delete from public.shipments where id=doc; exception when insufficient_privilege then blocked:=true; end;
 if not blocked then raise exception 'FAIL: hard delete allowed'; end if;
 execute 'reset role';
end $$;
rollback;
